apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-istio
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "istio"
spec:
  target: control-plane
  channel: regular
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: Istio
    metadata:
      name: istio-sample
      labels:
        app.kubernetes.io/name: istio-sample
    spec:
      config:
        numTrustedProxies: 1
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/istio
      provider: internal
      repositoryContexts:
      - baseUrl: ghcr.io/pbochynski/istio-module
        componentNameMapping: urlPath
        type: ociRegistry
      resources:
      - access:
          digest: sha256:f4a599c4310b0fe9133b67b72d9b15ee96b52a1872132528c83978239b5effef
          type: localOciBlob
        name: config
        relation: local
        type: yaml
        version: v0.2.0
      - access:
          digest: sha256:8bb34cfba9500c34b03c8cda417c1745360c622b4af683c2ffb72d6663435214
          type: localOciBlob
        name: istio
        relation: local
        type: helm-chart
        version: v0.2.0
      sources:
      - access:
          commit: 5cac2f91d85eb93d1a0dd8ff7d187968bbed9cb2
          repoUrl: github.com/kyma-project/istio
          type: gitHub
        labels:
        - name: git.kyma-project.io/ref
          value: refs/heads/main
          version: v1
        name: module-sources
        type: git
        version: v0.2.0
      version: v0.2.0
    meta:
      schemaVersion: v2