apiVersion: operator.kyma-project.io/v1beta1
kind: ModuleTemplate
metadata:
  name: moduletemplate-cluster-ip-fast
  namespace: kyma-system
  labels:
    "operator.kyma-project.io/managed-by": "lifecycle-manager"
    "operator.kyma-project.io/controller-name": "manifest"
    "operator.kyma-project.io/module-name": "cluster-ip"
spec:
  target: control-plane
  channel: fast
  data:
    apiVersion: operator.kyma-project.io/v1alpha1
    kind: ClusterIP
    metadata:
      name: clusterip-nodes
    spec:
      nodeSpreadLabel: kubernetes.io/hostname
  descriptor:
    component:
      componentReferences: []
      name: kyma-project.io/cluster-ip
      provider: internal
      repositoryContexts:
        - baseUrl: ghcr.io/pbochynski/cluster-ip-module
          componentNameMapping: urlPath
          type: ociRegistry
      resources:
        - access:
            digest: sha256:e212eee87097e6d9784c9af08b45533ab50aa628fd61d9c03ed37569601b9405
            type: localOciBlob
          name: config
          relation: local
          type: yaml
          version: v0.0.24
        - access:
            digest: sha256:4d6b006fa83f09088039fa744ddfb7e2e686115e4c8048d79a95343be7a81484
            type: localOciBlob
          name: cluster-ip
          relation: local
          type: helm-chart
          version: v0.0.24
      sources:
        - access:
            commit: df23364c3d43478c0dab6900a379bb345b1a98ba
            repoUrl: github.com/kyma-project/cluster-ip
            type: gitHub
          labels:
            - name: git.kyma-project.io/ref
              value: refs/heads/main
              version: v1
          name: module-sources
          type: git
          version: v0.0.24
      version: v0.0.24
    meta:
      schemaVersion: v2
